name: Apt based Linux (AArch64)
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian GNU/Linux buster arm64
          - Debian GNU/Linux bullseye arm64
          - Ubuntu Focal arm64
          - Ubuntu Jammy arm64
        include:
          - label: Debian GNU/Linux buster arm64
            rake-job: debian-buster
            test-docker-image: arm64v8/debian:buster
          - label: Debian GNU/Linux bullseye arm64
            rake-job: debian-bullseye
            test-docker-image: arm64v8/debian:bullseye
          - label: Ubuntu Focal arm64
            rake-job: ubuntu-focal
            rake-options: LINTIAN=no
            test-docker-image: arm64v8/ubuntu:focal
          - label: Ubuntu Jammy arm64
            rake-job: ubuntu-jammy
            rake-options: LINTIAN=no
            test-docker-image: arm64v8/ubuntu:jammy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: Build deb with Docker
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          rake apt:build APT_TARGETS=${{ matrix.rake-job }}-arm64 ${{ matrix.rake-options }}
      - name: Upload td-agent deb
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}-arm64
          path: td-agent/apt/repositories
      - name: Check Package Size
        run: |
          td-agent/apt/pkgsize-test.sh ${{ matrix.rake-job }} arm64
      - name: Binstubs Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/apt/binstubs-test.sh
