name: Windows
on: workflow_dispatch
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
    runs-on: windows-2019
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - uses: actions/checkout@master
      - name: Build
        run: |
          gem install serverspec
          gem install bundler:2.2.9 --no-document
          rake msi:build
      - name: Upload td-agent msi
        uses: actions/upload-artifact@master
        with:
          name: packages-windows-x86_64
          path: td-agent/msi/repositories
      - name: Check Package Size
        shell: pwsh
        run: |
          powershell -ExecutionPolicy Bypass -Command ".\td-agent\msi\pkgsize-test.ps1"
      - name: Installation Test
        shell: pwsh
        run: |
          mkdir -p .bundle
          docker run `
          --rm `
          --tty `
          --volume ${PWD}:C:\fluentd:ro `
          mcr.microsoft.com/dotnet/framework/runtime:3.5 `
          powershell -ExecutionPolicy Bypass -Command "C:\fluentd\td-agent\msi\install-test.ps1"
      - name: Serverspec Test
        shell: pwsh
        run: |
          docker run `
          --rm `
          --tty `
          --volume ${PWD}:C:\fluentd:ro `
          mcr.microsoft.com/dotnet/framework/runtime:3.5 `
          powershell -ExecutionPolicy Bypass -Command "C:\fluentd\td-agent\msi\serverspec-test.ps1"
