name: Yum based Linux
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - RockyLinux 8 x86_64
          - AlmaLinux 9 x86_64
          - Amazon Linux 2 x86_64
          - Amazon Linux 2022 x86_64
        include:
          - label: RockyLinux 8 x86_64
            rake-job: rockylinux-8
            test-docker-image: rockylinux/rockylinux:8
            centos-stream: false
          - label: AlmaLinux 9 x86_64
            rake-job: almalinux-9
            test-docker-image: almalinux:9
            centos-stream: false
          - label: Amazon Linux 2 x86_64
            rake-job: amazonlinux-2
            test-docker-image: amazonlinux:2
            centos-stream: false
          - label: Amazon Linux 2022 x86_64
            rake-job: amazonlinux-2022
            test-docker-image: amazonlinux:2022
            centos-stream: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: Build rpm with Docker
        run: |
          rake yum:build YUM_TARGETS=${{ matrix.rake-job }}
      - name: Upload td-agent rpm
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}
          path: td-agent/yum/repositories/**/Packages/td-agent-[0-9]*.rpm
      - name: Check Package Size
        run: |
          td-agent/yum/pkgsize-test.sh ${{ matrix.rake-job }} x86_64
      - name: Installation Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          --env CENTOS_STREAM=${{ matrix.centos-stream }} \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/yum/install-test.sh
      - name: Serverspec Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          --env CENTOS_STREAM=${{ matrix.centos-stream }} \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/yum/serverspec-test.sh
      - name: Binstubs Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          --env CENTOS_STREAM=${{ matrix.centos-stream }} \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/yum/binstubs-test.sh
